In [2]:
import requests
from bs4 import BeautifulSoup
import json
import pandas as pd
from datetime import datetime

In [3]:
# Step 1: Fetch the website
url = 'https://understat.com/league/EPL'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

In [4]:
# Step 2: Find the specific <script> tag containing the JSON data
scripts = soup.find_all('script')
json_data = None

In [5]:
# Step 3: Look for the script containing the teamsData
for script in scripts:
    if 'teamsData' in script.text:
        # Extract the content of the script tag as text
        json_text = script.text
        # Step 4: Isolate the JSON data by splitting the string
        json_text = json_text.split("JSON.parse('")[1].split("')")[0]
        # Step 5: Decode the string by replacing escape characters
        json_text = json_text.encode('utf-8').decode('unicode_escape')
        # Step 6: Load the decoded text as a Python dictionary
        json_data = json.loads(json_text)
        break

In [6]:
json_data

{'71': {'id': '71',
  'title': 'Aston Villa',
  'history': [{'h_a': 'a',
    'xG': 2.6703,
    'xGA': 2.8047,
    'npxG': 2.6703,
    'npxGA': 2.04353,
    'ppda': {'att': 260, 'def': 23},
    'ppda_allowed': {'att': 224, 'def': 24},
    'deep': 8,
    'deep_allowed': 5,
    'scored': 2,
    'missed': 1,
    'xpts': 1.2989000000000002,
    'result': 'w',
    'date': '2024-08-17 16:30:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 0.62677},
   {'h_a': 'h',
    'xG': 1.31664,
    'xGA': 1.41399,
    'npxG': 1.31664,
    'npxGA': 1.41399,
    'ppda': {'att': 311, 'def': 18},
    'ppda_allowed': {'att': 175, 'def': 30},
    'deep': 3,
    'deep_allowed': 10,
    'scored': 0,
    'missed': 2,
    'xpts': 1.2362000000000002,
    'result': 'l',
    'date': '2024-08-24 16:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -0.09735000000000005},
   {'h_a': 'a',
    'xG': 2.16385,
    'xGA': 0.774741,
    'npxG': 2.16385,
    'npxGA': 0.774741,
    'ppda': {'att': 314, 'def': 30},
    'ppda_allowed': {'att': 224, 'def': 35},
    'deep': 6,
    'deep_allowed': 3,
    'scored': 2,
    'missed': 1,
    'xpts': 2.448,
    'result': 'w',
    'date': '2024-08-31 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 1.389109},
   {'h_a': 'h',
    'xG': 3.15876,
    'xGA': 0.852158,
    'npxG': 3.15876,
    'npxGA': 0.852158,
    'ppda': {'att': 121, 'def': 23},
    'ppda_allowed': {'att': 294, 'def': 18},
    'deep': 9,
    'deep_allowed': 3,
    'scored': 3,
    'missed': 2,
    'xpts': 2.7595,
    'result': 'w',
    'date': '2024-09-14 16:30:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 2.306602},
   {'h_a': 'h',
    'xG': 2.37351,
    'xGA': 0.520117,
    'npxG': 2.37351,
    'npxGA': 0.520117,
    'ppda': {'att': 236, 'def': 20},
    'ppda_allowed': {'att': 216, 'def': 16},
    'deep': 9,
    'deep_allowed': 4,
    'scored': 3,
    'missed': 1,
    'xpts': 2.6481,
    'result': 'w',
    'date': '2024-09-21 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 1.853393},
   {'h_a': 'a',
    'xG': 1.14494,
    'xGA': 1.84608,
    'npxG': 1.14494,
    'npxGA': 1.84608,
    'ppda': {'att': 262, 'def': 22},
    'ppda_allowed': {'att': 265, 'def': 16},
    'deep': 5,
    'deep_allowed': 6,
    'scored': 2,
    'missed': 2,
    'xpts': 0.8247,
    'result': 'd',
    'date': '2024-09-29 13:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.7011399999999999},
   {'h_a': 'h',
    'xG': 0.532809,
    'xGA': 0.448537,
    'npxG': 0.532809,
    'npxGA': 0.448537,
    'ppda': {'att': 199, 'def': 14},
    'ppda_allowed': {'att': 236, 'def': 17},
    'deep': 9,
    'deep_allowed': 1,
    'scored': 0,
    'missed': 0,
    'xpts': 1.3408,
    'result': 'd',
    'date': '2024-10-06 13:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 0.08427199999999996},
   {'h_a': 'a',
    'xG': 1.43595,
    'xGA': 2.63074,
    'npxG': 1.43595,
    'npxGA': 1.86957,
    'ppda': {'att': 252, 'def': 15},
    'ppda_allowed': {'att': 247, 'def': 20},
    'deep': 9,
    'deep_allowed': 3,
    'scored': 3,
    'missed': 1,
    'xpts': 0.5631,
    'result': 'w',
    'date': '2024-10-19 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': -0.4336199999999999},
   {'h_a': 'h',
    'xG': 1.974,
    'xGA': 0.328651,
    'npxG': 1.974,
    'npxGA': 0.328651,
    'ppda': {'att': 186, 'def': 18},
    'ppda_allowed': {'att': 229, 'def': 26},
    'deep': 16,
    'deep_allowed': 6,
    'scored': 1,
    'missed': 1,
    'xpts': 2.5907999999999998,
    'result': 'd',
    'date': '2024-10-26 14:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 1.645349},
   {'h_a': 'a',
    'xG': 2.48749,
    'xGA': 2.09751,
    'npxG': 2.48749,
    'npxGA': 2.09751,
    'ppda': {'att': 178, 'def': 17},
    'ppda_allowed': {'att': 234, 'def': 43},
    'deep': 3,
    'deep_allowed': 11,
    'scored': 1,
    'missed': 4,
    'xpts': 1.6758,
    'result': 'l',
    'date': '2024-11-03 14:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': 0.38998},
   {'h_a': 'a',
    'xG': 1.66337,
    'xGA': 2.68196,
    'npxG': 1.66337,
    'npxGA': 2.68196,
    'ppda': {'att': 389, 'def': 22},
    'ppda_allowed': {'att': 224, 'def': 26},
    'deep': 4,
    'deep_allowed': 7,
    'scored': 0,
    'missed': 2,
    'xpts': 0.7257,
    'result': 'l',
    'date': '2024-11-09 20:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.01859},
   {'h_a': 'h',
    'xG': 3.04455,
    'xGA': 1.61437,
    'npxG': 2.28338,
    'npxGA': 1.61437,
    'ppda': {'att': 111, 'def': 15},
    'ppda_allowed': {'att': 348, 'def': 22},
    'deep': 11,
    'deep_allowed': 2,
    'scored': 2,
    'missed': 2,
    'xpts': 2.3213,
    'result': 'd',
    'date': '2024-11-23 15:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 0.6690100000000001},
   {'h_a': 'a',
    'xG': 0.875443,
    'xGA': 1.94939,
    'npxG': 0.875443,
    'npxGA': 1.94939,
    'ppda': {'att': 396, 'def': 10},
    'ppda_allowed': {'att': 243, 'def': 30},
    'deep': 4,
    'deep_allowed': 4,
    'scored': 0,
    'missed': 3,
    'xpts': 0.6308,
    'result': 'l',
    'date': '2024-12-01 13:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.073947},
   {'h_a': 'h',
    'xG': 3.21673,
    'xGA': 1.13266,
    'npxG': 2.45556,
    'npxGA': 1.13266,
    'ppda': {'att': 211, 'def': 19},
    'ppda_allowed': {'att': 225, 'def': 31},
    'deep': 11,
    'deep_allowed': 5,
    'scored': 3,
    'missed': 1,
    'xpts': 2.6043000000000003,
    'result': 'w',
    'date': '2024-12-04 20:15:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 1.3229000000000002},
   {'h_a': 'h',
    'xG': 2.51338,
    'xGA': 0.385832,
    'npxG': 2.51338,
    'npxGA': 0.385832,
    'ppda': {'att': 276, 'def': 35},
    'ppda_allowed': {'att': 239, 'def': 27},
    'deep': 13,
    'deep_allowed': 7,
    'scored': 1,
    'missed': 0,
    'xpts': 2.7499,
    'result': 'w',
    'date': '2024-12-07 15:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 2.127548},
   {'h_a': 'a',
    'xG': 0.389423,
    'xGA': 2.2861,
    'npxG': 0.389423,
    'npxGA': 2.2861,
    'ppda': {'att': 237, 'def': 14},
    'ppda_allowed': {'att': 277, 'def': 16},
    'deep': 7,
    'deep_allowed': 5,
    'scored': 1,
    'missed': 2,
    'xpts': 0.198,
    'result': 'l',
    'date': '2024-12-14 17:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.8966769999999997},
   {'h_a': 'h',
    'xG': 2.05988,
    'xGA': 1.09627,
    'npxG': 2.05988,
    'npxGA': 1.09627,
    'ppda': {'att': 257, 'def': 14},
    'ppda_allowed': {'att': 294, 'def': 15},
    'deep': 7,
    'deep_allowed': 4,
    'scored': 2,
    'missed': 1,
    'xpts': 2.0925,
    'result': 'w',
    'date': '2024-12-21 12:30:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 0.9636100000000001},
   {'h_a': 'a',
    'xG': 0.225522,
    'xGA': 2.82867,
    'npxG': 0.225522,
    'npxGA': 2.82867,
    'ppda': {'att': 304, 'def': 14},
    'ppda_allowed': {'att': 171, 'def': 28},
    'deep': 2,
    'deep_allowed': 20,
    'scored': 0,
    'missed': 3,
    'xpts': 0.0707,
    'result': 'l',
    'date': '2024-12-26 15:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -2.603148},
   {'h_a': 'h',
    'xG': 1.87997,
    'xGA': 0.938042,
    'npxG': 1.1188,
    'npxGA': 0.938042,
    'ppda': {'att': 199, 'def': 20},
    'ppda_allowed': {'att': 275, 'def': 32},
    'deep': 13,
    'deep_allowed': 6,
    'scored': 2,
    'missed': 2,
    'xpts': 2.1243,
    'result': 'd',
    'date': '2024-12-30 19:45:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 0.18075799999999997},
   {'h_a': 'h',
    'xG': 2.3456,
    'xGA': 0.81548,
    'npxG': 2.3456,
    'npxGA': 0.81548,
    'ppda': {'att': 262, 'def': 29},
    'ppda_allowed': {'att': 396, 'def': 19},
    'deep': 9,
    'deep_allowed': 3,
    'scored': 2,
    'missed': 1,
    'xpts': 2.5573,
    'result': 'w',
    'date': '2025-01-04 15:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 1.5301200000000001},
   {'h_a': 'a',
    'xG': 1.28522,
    'xGA': 1.23126,
    'npxG': 1.28522,
    'npxGA': 1.23126,
    'ppda': {'att': 219, 'def': 15},
    'ppda_allowed': {'att': 271, 'def': 28},
    'deep': 5,
    'deep_allowed': 4,
    'scored': 1,
    'missed': 0,
    'xpts': 1.3870999999999998,
    'result': 'w',
    'date': '2025-01-15 19:30:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 0.05396000000000001},
   {'h_a': 'a',
    'xG': 1.20602,
    'xGA': 1.64458,
    'npxG': 1.20602,
    'npxGA': 1.64458,
    'ppda': {'att': 210, 'def': 14},
    'ppda_allowed': {'att': 150, 'def': 22},
    'deep': 1,
    'deep_allowed': 8,
    'scored': 2,
    'missed': 2,
    'xpts': 1.0373999999999999,
    'result': 'd',
    'date': '2025-01-18 17:30:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.43855999999999984},
   {'h_a': 'h',
    'xG': 0.907851,
    'xGA': 1.67886,
    'npxG': 0.907851,
    'npxGA': 1.67886,
    'ppda': {'att': 269, 'def': 31},
    'ppda_allowed': {'att': 196, 'def': 31},
    'deep': 7,
    'deep_allowed': 5,
    'scored': 1,
    'missed': 1,
    'xpts': 0.7566999999999999,
    'result': 'd',
    'date': '2025-01-26 16:30:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.771009},
   {'h_a': 'a',
    'xG': 0.742809,
    'xGA': 2.00146,
    'npxG': 0.742809,
    'npxGA': 2.00146,
    'ppda': {'att': 161, 'def': 14},
    'ppda_allowed': {'att': 294, 'def': 24},
    'deep': 4,
    'deep_allowed': 2,
    'scored': 0,
    'missed': 2,
    'xpts': 0.45170000000000005,
    'result': 'l',
    'date': '2025-02-01 17:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.2586509999999997}]},
 '72': {'id': '72',
  'title': 'Everton',
  'history': [{'h_a': 'h',
    'xG': 0.405325,
    'xGA': 1.79083,
    'npxG': 0.405325,
    'npxGA': 1.79083,
    'ppda': {'att': 385, 'def': 21},
    'ppda_allowed': {'att': 190, 'def': 24},
    'deep': 4,
    'deep_allowed': 5,
    'scored': 0,
    'missed': 3,
    'xpts': 0.30779999999999996,
    'result': 'l',
    'date': '2024-08-17 14:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.385505},
   {'h_a': 'a',
    'xG': 0.648869,
    'xGA': 2.61143,
    'npxG': 0.648869,
    'npxGA': 2.61143,
    'ppda': {'att': 369, 'def': 29},
    'ppda_allowed': {'att': 126, 'def': 20},
    'deep': 5,
    'deep_allowed': 9,
    'scored': 0,
    'missed': 4,
    'xpts': 0.2558,
    'result': 'l',
    'date': '2024-08-24 14:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.962561},
   {'h_a': 'h',
    'xG': 2.55629,
    'xGA': 2.95688,
    'npxG': 2.55629,
    'npxGA': 2.95688,
    'ppda': {'att': 191, 'def': 23},
    'ppda_allowed': {'att': 149, 'def': 21},
    'deep': 15,
    'deep_allowed': 7,
    'scored': 2,
    'missed': 3,
    'xpts': 1.1241,
    'result': 'l',
    'date': '2024-08-31 14:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -0.4005899999999998},
   {'h_a': 'a',
    'xG': 0.852158,
    'xGA': 3.15876,
    'npxG': 0.852158,
    'npxGA': 3.15876,
    'ppda': {'att': 294, 'def': 18},
    'ppda_allowed': {'att': 121, 'def': 23},
    'deep': 3,
    'deep_allowed': 9,
    'scored': 2,
    'missed': 3,
    'xpts': 0.1567,
    'result': 'l',
    'date': '2024-09-14 16:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -2.306602},
   {'h_a': 'a',
    'xG': 1.82377,
    'xGA': 1.33793,
    'npxG': 1.82377,
    'npxGA': 1.33793,
    'ppda': {'att': 251, 'def': 13},
    'ppda_allowed': {'att': 160, 'def': 19},
    'deep': 6,
    'deep_allowed': 8,
    'scored': 1,
    'missed': 1,
    'xpts': 1.6985,
    'result': 'd',
    'date': '2024-09-21 14:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 0.4858399999999998},
   {'h_a': 'h',
    'xG': 1.10959,
    'xGA': 1.12358,
    'npxG': 1.10959,
    'npxGA': 1.12358,
    'ppda': {'att': 300, 'def': 24},
    'ppda_allowed': {'att': 168, 'def': 18},
    'deep': 6,
    'deep_allowed': 8,
    'scored': 2,
    'missed': 1,
    'xpts': 1.3309,
    'result': 'w',
    'date': '2024-09-28 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': -0.013989999999999947},
   {'h_a': 'h',
    'xG': 0.692214,
    'xGA': 1.79048,
    'npxG': 0.692214,
    'npxGA': 1.02931,
    'ppda': {'att': 410, 'def': 26},
    'ppda_allowed': {'att': 164, 'def': 28},
    'deep': 3,
    'deep_allowed': 11,
    'scored': 0,
    'missed': 0,
    'xpts': 0.4902,
    'result': 'd',
    'date': '2024-10-05 16:30:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.33709599999999995},
   {'h_a': 'a',
    'xG': 1.60804,
    'xGA': 1.174,
    'npxG': 1.60804,
    'npxGA': 1.174,
    'ppda': {'att': 302, 'def': 19},
    'ppda_allowed': {'att': 240, 'def': 21},
    'deep': 9,
    'deep_allowed': 3,
    'scored': 2,
    'missed': 0,
    'xpts': 1.717,
    'result': 'w',
    'date': '2024-10-19 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 0.43404},
   {'h_a': 'h',
    'xG': 0.884845,
    'xGA': 1.49531,
    'npxG': 0.884845,
    'npxGA': 1.49531,
    'ppda': {'att': 360, 'def': 17},
    'ppda_allowed': {'att': 219, 'def': 20},
    'deep': 7,
    'deep_allowed': 7,
    'scored': 1,
    'missed': 1,
    'xpts': 0.8440000000000001,
    'result': 'd',
    'date': '2024-10-26 16:30:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.6104649999999999},
   {'h_a': 'a',
    'xG': 1.78581,
    'xGA': 0.540345,
    'npxG': 1.78581,
    'npxGA': 0.540345,
    'ppda': {'att': 390, 'def': 26},
    'ppda_allowed': {'att': 157, 'def': 17},
    'deep': 4,
    'deep_allowed': 6,
    'scored': 0,
    'missed': 1,
    'xpts': 2.3625,
    'result': 'l',
    'date': '2024-11-02 15:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': 1.2454649999999998},
   {'h_a': 'a',
    'xG': 0.865983,
    'xGA': 1.1237,
    'npxG': 0.865983,
    'npxGA': 1.1237,
    'ppda': {'att': 200, 'def': 18},
    'ppda_allowed': {'att': 213, 'def': 21},
    'deep': 7,
    'deep_allowed': 8,
    'scored': 0,
    'missed': 0,
    'xpts': 1.0962,
    'result': 'd',
    'date': '2024-11-09 15:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.257717},
   {'h_a': 'h',
    'xG': 1.5951,
    'xGA': 1.34314,
    'npxG': 1.5951,
    'npxGA': 1.34314,
    'ppda': {'att': 223, 'def': 15},
    'ppda_allowed': {'att': 183, 'def': 23},
    'deep': 8,
    'deep_allowed': 1,
    'scored': 0,
    'missed': 0,
    'xpts': 1.5025,
    'result': 'd',
    'date': '2024-11-23 15:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': 0.25195999999999996},
   {'h_a': 'a',
    'xG': 0.766749,
    'xGA': 1.76161,
    'npxG': 0.766749,
    'npxGA': 1.76161,
    'ppda': {'att': 461, 'def': 27},
    'ppda_allowed': {'att': 275, 'def': 24},
    'deep': 3,
    'deep_allowed': 10,
    'scored': 0,
    'missed': 4,
    'xpts': 0.5986,
    'result': 'l',
    'date': '2024-12-01 13:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -0.9948609999999999},
   {'h_a': 'h',
    'xG': 1.49904,
    'xGA': 0.847724,
    'npxG': 1.49904,
    'npxGA': 0.847724,
    'ppda': {'att': 285, 'def': 28},
    'ppda_allowed': {'att': 185, 'def': 24},
    'deep': 7,
    'deep_allowed': 4,
    'scored': 4,
    'missed': 0,
    'xpts': 1.8867999999999998,
    'result': 'w',
    'date': '2024-12-04 19:30:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 0.6513159999999999},
   {'h_a': 'a',
    'xG': 0.132166,
    'xGA': 1.30865,
    'npxG': 0.132166,
    'npxGA': 1.30865,
    'ppda': {'att': 356, 'def': 18},
    'ppda_allowed': {'att': 106, 'def': 21},
    'deep': 2,
    'deep_allowed': 12,
    'scored': 0,
    'missed': 0,
    'xpts': 0.3379,
    'result': 'd',
    'date': '2024-12-14 15:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -1.176484},
   {'h_a': 'h',
    'xG': 1.07081,
    'xGA': 1.51591,
    'npxG': 1.07081,
    'npxGA': 1.51591,
    'ppda': {'att': 404, 'def': 28},
    'ppda_allowed': {'att': 110, 'def': 23},
    'deep': 0,
    'deep_allowed': 2,
    'scored': 0,
    'missed': 0,
    'xpts': 0.9176,
    'result': 'd',
    'date': '2024-12-22 14:00:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -0.44510000000000005},
   {'h_a': 'a',
    'xG': 0.653289,
    'xGA': 2.51965,
    'npxG': 0.653289,
    'npxGA': 1.75849,
    'ppda': {'att': 309, 'def': 11},
    'ppda_allowed': {'att': 192, 'def': 18},
    'deep': 1,
    'deep_allowed': 18,
    'scored': 1,
    'missed': 1,
    'xpts': 0.2591,
    'result': 'd',
    'date': '2024-12-26 12:30:00',
    'wins': 0,
    'draws': 1,
    'loses': 0,
    'pts': 1,
    'npxGD': -1.105201},
   {'h_a': 'h',
    'xG': 0.615191,
    'xGA': 2.02753,
    'npxG': 0.615191,
    'npxGA': 2.02753,
    'ppda': {'att': 131, 'def': 16},
    'ppda_allowed': {'att': 221, 'def': 13},
    'deep': 8,
    'deep_allowed': 7,
    'scored': 0,
    'missed': 2,
    'xpts': 0.38470000000000004,
    'result': 'l',
    'date': '2024-12-29 15:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -1.412339},
   {'h_a': 'a',
    'xG': 0.561015,
    'xGA': 2.61852,
    'npxG': 0.561015,
    'npxGA': 2.61852,
    'ppda': {'att': 193, 'def': 18},
    'ppda_allowed': {'att': 107, 'def': 27},
    'deep': 1,
    'deep_allowed': 14,
    'scored': 0,
    'missed': 1,
    'xpts': 0.17420000000000002,
    'result': 'l',
    'date': '2025-01-04 15:00:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -2.057505},
   {'h_a': 'h',
    'xG': 1.23126,
    'xGA': 1.28522,
    'npxG': 1.23126,
    'npxGA': 1.28522,
    'ppda': {'att': 271, 'def': 28},
    'ppda_allowed': {'att': 219, 'def': 15},
    'deep': 4,
    'deep_allowed': 5,
    'scored': 0,
    'missed': 1,
    'xpts': 1.3195999999999999,
    'result': 'l',
    'date': '2025-01-15 19:30:00',
    'wins': 0,
    'draws': 0,
    'loses': 1,
    'pts': 0,
    'npxGD': -0.05396000000000001},
   {'h_a': 'h',
    'xG': 2.56089,
    'xGA': 1.35719,
    'npxG': 2.56089,
    'npxGA': 1.35719,
    'ppda': {'att': 337, 'def': 28},
    'ppda_allowed': {'att': 171, 'def': 19},
    'deep': 6,
    'deep_allowed': 8,
    'scored': 3,
    'missed': 2,
    'xpts': 2.1962,
    'result': 'w',
    'date': '2025-01-19 14:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 1.2037000000000002},
   {'h_a': 'a',
    'xG': 0.870883,
    'xGA': 0.64378,
    'npxG': 0.109715,
    'npxGA': 0.64378,
    'ppda': {'att': 317, 'def': 19},
    'ppda_allowed': {'att': 174, 'def': 26},
    'deep': 2,
    'deep_allowed': 9,
    'scored': 1,
    'missed': 0,
    'xpts': 1.6616,
    'result': 'w',
    'date': '2025-01-25 15:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': -0.534065},
   {'h_a': 'h',
    'xG': 3.11261,
    'xGA': 0.447136,
    'npxG': 3.11261,
    'npxGA': 0.447136,
    'ppda': {'att': 323, 'def': 18},
    'ppda_allowed': {'att': 277, 'def': 23},
    'deep': 14,
    'deep_allowed': 4,
    'scored': 4,
    'missed': 0,
    'xpts': 2.845,
    'result': 'w',
    'date': '2025-02-01 15:00:00',
    'wins': 1,
    'draws': 0,
    'loses': 0,
    'pts': 3,
    'npxGD': 2.665474}]},
 '73': {'id': '73',
  'title': 'Bournemouth',

In [7]:
# Step 7: Extract match data for each team and identify the opponent
data = []

# Step 8: Create a reverse lookup dictionary for matches based on date and home/away status
matches_by_date = {}

for team_id, team_info in json_data.items():
    team_name = team_info['title']
    for match in team_info['history']:
        if match['h_a'] == 'h':
            match_key = (match['date'], match['xG'], match['xGA'])
        else:
            match_key = (match['date'], match['xGA'], match['xG'])

        if match_key not in matches_by_date:
            matches_by_date[match_key] = []
        matches_by_date[match_key].append({
            'team': team_name,
            'xG': match['xG'],
            'xGA': match['xGA'],
            'scored': match['scored'],
            'missed': match['missed'],
            'result': match['result'],
            'pts': match['pts'],
            'h_a': match['h_a']  # home/away status
        })

In [8]:
# Step 9: Construct final data with opponents
for match_key, matches in matches_by_date.items():
    if len(matches) == 2:
        # We found both home and away team for the match
        home_match = [m for m in matches if m['h_a'] == 'h'][0]
        away_match = [m for m in matches if m['h_a'] == 'a'][0]
        
        # Add home team data with away team as opponent
        data.append({
            'team': home_match['team'],
            'opponent': away_match['team'],
            'date': match_key[0],
            'xG': home_match['xG'],
            'xGA': home_match['xGA'],
            'scored': home_match['scored'],
            'missed': home_match['missed'],
            'result': home_match['result'],
            'pts': home_match['pts']
        })
        
        # Add away team data with home team as opponent
        data.append({
            'team': away_match['team'],
            'opponent': home_match['team'],
            'date': match_key[0],
            'xG': away_match['xG'],
            'xGA': away_match['xGA'],
            'scored': away_match['scored'],
            'missed': away_match['missed'],
            'result': away_match['result'],
            'pts': away_match['pts']
        })

In [9]:
# Step 10: Convert the list of match data into a pandas DataFrame
df = pd.DataFrame(data)
df

,team,opponent,date,xG,xGA,scored,missed,result,pts
0,West Ham,Aston Villa,2024-08-17 16:30:00,2.804700,2.670300,1,2,l,0
1,Aston Villa,West Ham,2024-08-17 16:30:00,2.670300,2.804700,2,1,w,3
2,Aston Villa,Arsenal,2024-08-24 16:30:00,1.316640,1.413990,0,2,l,0
3,Arsenal,Aston Villa,2024-08-24 16:30:00,1.413990,1.316640,2,0,w,3
4,Leicester,Aston Villa,2024-08-31 14:00:00,0.774741,2.163850,1,2,l,0
...,...,...,...,...,...,...,...,...,...
471,Ipswich,Brentford,2024-10-26 14:00:00,1.656980,4.096630,3,4,l,0
472,Brentford,Nottingham Forest,2024-12-21 15:00:00,0.769004,0.964897,0,2,l,0
473,Nottingham Forest,Brentford,2024-12-21 15:00:00,0.964897,0.769004,2,0,w,3
474,Nottingham Forest,Ipswich,2024-11-30 15:00:00,1.765870,0.462771,1,0,w,3
475,Ipswich,Nottingham Forest,2024-11-30 15:00:00,0.462771,1.765870,0,1,l,0

In [10]:
df[df['date'] > datetime.now().strftime("%Y-%m-%d %H:%M:%S")]

Empty DataFrame
Columns: [team, opponent, date, xG, xGA, scored, missed, result, pts]
Index: []

In [11]:
df['date'].max()

'2025-02-02 16:30:00'

## Dates Data

In [12]:
# Step 3: Look for the script containing the teamsData
for script in scripts:
    if 'datesData' in script.text:
        # Extract the content of the script tag as text
        dates_json_text = script.text
        # Step 4: Isolate the JSON data by splitting the string
        dates_json_text = dates_json_text.split("JSON.parse('")[1].split("')")[0]
        # Step 5: Decode the string by replacing escape characters
        dates_json_text = dates_json_text.encode('utf-8').decode('unicode_escape')
        # Step 6: Load the decoded text as a Python dictionary
        dates_json_data = json.loads(dates_json_text)
        break

In [13]:
dates_json_data

[{'id': '26602',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.04268', 'a': '0.418711'},
  'datetime': '2024-08-16 19:00:00',
  'forecast': {'w': '0.8069', 'd': '0.1489', 'l': '0.0442'}},
 {'id': '26603',
  'isResult': True,
  'h': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '0.342601', 'a': '3.92906'},
  'datetime': '2024-08-17 11:30:00',
  'forecast': {'w': '0.0026', 'd': '0.018', 'l': '0.9794'}},
 {'id': '26604',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '1.6283', 'a': '0.575835'},
  'datetime': '2024-08-17 14:00:00',
  'forecast': {'w': '0.6528', 'd': '0.231', 'l': '0.1162'}},
 {'id': '26605',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '0.405325', 'a': '1.79083'},
  'datetime': '2024-08-17 14:00:00',
  'forecast': {'w': '0.0481', 'd': '0.1635', 'l': '0.7884'}},
 {'id': '26606',
  'isResult': True,
  'h': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'a': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '0.433489', 'a': '1.95483'},
  'datetime': '2024-08-17 14:00:00',
  'forecast': {'w': '0.0378', 'd': '0.164', 'l': '0.7982'}},
 {'id': '26607',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.24405', 'a': '1.90915'},
  'datetime': '2024-08-17 14:00:00',
  'forecast': {'w': '0.1994', 'd': '0.2537', 'l': '0.5469'}},
 {'id': '26608',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '2.8047', 'a': '2.6703'},
  'datetime': '2024-08-17 16:30:00',
  'forecast': {'w': '0.4123', 'd': '0.2321', 'l': '0.3556'}},
 {'id': '26609',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.38064', 'a': '1.14757'},
  'datetime': '2024-08-18 13:00:00',
  'forecast': {'w': '0.4248', 'd': '0.3141', 'l': '0.2611'}},
 {'id': '26610',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '1.06123', 'a': '1.18038'},
  'datetime': '2024-08-18 15:30:00',
  'forecast': {'w': '0.3036', 'd': '0.3245', 'l': '0.3719'}},
 {'id': '26611',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.02614', 'a': '1.40775'},
  'datetime': '2024-08-19 19:00:00',
  'forecast': {'w': '0.2541', 'd': '0.2951', 'l': '0.4508'}},
 {'id': '26612',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '2.14153', 'a': '1.28556'},
  'datetime': '2024-08-24 11:30:00',
  'forecast': {'w': '0.601', 'd': '0.2392', 'l': '0.1598'}},
 {'id': '26613',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '1.3761', 'a': '1.53421'},
  'datetime': '2024-08-24 14:00:00',
  'forecast': {'w': '0.3315', 'd': '0.2678', 'l': '0.4007'}},
 {'id': '26614',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.96218', 'a': '0.857005'},
  'datetime': '2024-08-24 14:00:00',
  'forecast': {'w': '0.6596', 'd': '0.215', 'l': '0.1254'}},
 {'id': '26615',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'goals': {'h': '4', 'a': '1'},
  'xG': {'h': '3.07818', 'a': '0.479999'},
  'datetime': '2024-08-24 14:00:00',
  'forecast': {'w': '0.9435', 'd': '0.0503', 'l': '0.0062'}},
 {'id': '26616',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.214952', 'a': '2.86475'},
  'datetime': '2024-08-24 14:00:00',
  'forecast': {'w': '0.0067', 'd': '0.0496', 'l': '0.9437'}},
 {'id': '26617',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '4', 'a': '0'},
  'xG': {'h': '2.61143', 'a': '0.648869'},
  'datetime': '2024-08-24 14:00:00',
  'forecast': {'w': '0.8398', 'd': '0.1124', 'l': '0.0478'}},
 {'id': '26618',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '1.31664', 'a': '1.41399'},
  'datetime': '2024-08-24 16:30:00',
  'forecast': {'w': '0.3113', 'd': '0.3023', 'l': '0.3864'}},
 {'id': '26619',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '2', 'a': '6'},
  'xG': {'h': '2.4181', 'a': '2.02935'},
  'datetime': '2024-08-25 13:00:00',
  'forecast': {'w': '0.4888', 'd': '0.2228', 'l': '0.2884'}},
 {'id': '26620',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.53513', 'a': '1.89287'},
  'datetime': '2024-08-25 13:00:00',
  'forecast': {'w': '0.5396', 'd': '0.2334', 'l': '0.227'}},
 {'id': '26621',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '2.71877', 'a': '0.457239'},
  'datetime': '2024-08-25 15:30:00',
  'forecast': {'w': '0.8893', 'd': '0.0893', 'l': '0.0214'}},
 {'id': '26622',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.41798', 'a': '1.81748'},
  'datetime': '2024-08-31 11:30:00',
  'forecast': {'w': '0.5278', 'd': '0.2236', 'l': '0.2486'}},
 {'id': '26623',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '3.86281', 'a': '1.64713'},
  'datetime': '2024-08-31 14:00:00',
  'forecast': {'w': '0.8348', 'd': '0.1027', 'l': '0.0625'}},
 {'id': '26624',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '2', 'a': '3'},
  'xG': {'h': '2.55629', 'a': '2.95688'},
  'datetime': '2024-08-31 14:00:00',
  'forecast': {'w': '0.3027', 'd': '0.216', 'l': '0.4813'}},
 {'id': '26625',
  'isResult': True,
  'h': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.707048', 'a': '1.18883'},
  'datetime': '2024-08-31 14:00:00',
  'forecast': {'w': '0.2034', 'd': '0.3116', 'l': '0.485'}},
 {'id': '26626',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.774741', 'a': '2.16385'},
  'datetime': '2024-08-31 14:00:00',
  'forecast': {'w': '0.0646', 'd': '0.1791', 'l': '0.7563'}},
 {'id': '26627',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.41069', 'a': '0.937632'},
  'datetime': '2024-08-31 14:00:00',
  'forecast': {'w': '0.4728', 'd': '0.3229', 'l': '0.2043'}},
 {'id': '26628',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '0.947201', 'a': '3.19297'},
  'datetime': '2024-08-31 16:30:00',
  'forecast': {'w': '0.0483', 'd': '0.1075', 'l': '0.8442'}},
 {'id': '26629',
  'isResult': True,
  'h': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.58694', 'a': '1.63304'},
  'datetime': '2024-09-01 12:30:00',
  'forecast': {'w': '0.3519', 'd': '0.2857', 'l': '0.3624'}},
 {'id': '26630',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.97743', 'a': '0.459708'},
  'datetime': '2024-09-01 12:30:00',
  'forecast': {'w': '0.9429', 'd': '0.0461', 'l': '0.011'}},
 {'id': '26631',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '1.50087', 'a': '2.10397'},
  'datetime': '2024-09-01 15:00:00',
  'forecast': {'w': '0.2409', 'd': '0.2462', 'l': '0.5129'}},
 {'id': '26632',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '1.35593', 'a': '3.02693'},
  'datetime': '2024-09-14 11:30:00',
  'forecast': {'w': '0.0634', 'd': '0.1533', 'l': '0.7833'}},
 {'id': '26633',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '1.75696', 'a': '0.721323'},
  'datetime': '2024-09-14 14:00:00',
  'forecast': {'w': '0.6638', 'd': '0.2448', 'l': '0.0914'}},
 {'id': '26634',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.88601', 'a': '0.682719'},
  'datetime': '2024-09-14 14:00:00',
  'forecast': {'w': '0.8681', 'd': '0.0971', 'l': '0.0348'}},
 {'id': '26635',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '1.17044', 'a': '0.589532'},
  'datetime': '2024-09-14 14:00:00',
  'forecast': {'w': '0.5221', 'd': '0.3244', 'l': '0.1535'}},
 {'id': '26636',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '2.88716', 'a': '1.65187'},
  'datetime': '2024-09-14 14:00:00',
  'forecast': {'w': '0.6779', 'd': '0.1869', 'l': '0.1352'}},
 {'id': '26637',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.55279', 'a': '1.05094'},
  'datetime': '2024-09-14 14:00:00',
  'forecast': {'w': '0.4771', 'd': '0.2847', 'l': '0.2382'}},
 {'id': '26638',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '3', 'a': '2'},
  'xG': {'h': '3.15876', 'a': '0.852158'},
  'datetime': '2024-09-14 16:30:00',
  'forecast': {'w': '0.8919', 'd': '0.0838', 'l': '0.0243'}},
 {'id': '26639',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '1.53731', 'a': '0.932726'},
  'datetime': '2024-09-14 19:00:00',
  'forecast': {'w': '0.5298', 'd': '0.2902', 'l': '0.18'}},
 {'id': '26640',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.792595', 'a': '1.1209'},
  'datetime': '2024-09-15 13:00:00',
  'forecast': {'w': '0.234', 'd': '0.3157', 'l': '0.4503'}},
 {'id': '26641',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '1.46969', 'a': '1.48343'},
  'datetime': '2024-09-15 15:30:00',
  'forecast': {'w': '0.3576', 'd': '0.2692', 'l': '0.3732'}},
 {'id': '26642',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '0.758267', 'a': '2.39727'},
  'datetime': '2024-09-21 11:30:00',
  'forecast': {'w': '0.0778', 'd': '0.15', 'l': '0.7722'}},
 {'id': '26643',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.89813', 'a': '1.645'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.6951', 'd': '0.1778', 'l': '0.1271'}},
 {'id': '26644',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.33793', 'a': '1.82377'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.2591', 'd': '0.2621', 'l': '0.4788'}},
 {'id': '26645',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '2.43731', 'a': '1.46979'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.597', 'd': '0.2063', 'l': '0.1967'}},
 {'id': '26646',
  'isResult': True,
  'h': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'a': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '3.21141', 'a': '1.09768'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.8274', 'd': '0.1124', 'l': '0.0602'}},
 {'id': '26647',
  'isResult': True,
  'h': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'a': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '2.37351', 'a': '0.520117'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.8449', 'd': '0.1134', 'l': '0.0417'}},
 {'id': '26648',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '3.89481', 'a': '0.893565'},
  'datetime': '2024-09-21 14:00:00',
  'forecast': {'w': '0.9397', 'd': '0.0464', 'l': '0.0139'}},
 {'id': '26649',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '1.66928', 'a': '2.35056'},
  'datetime': '2024-09-21 16:30:00',
  'forecast': {'w': '0.2248', 'd': '0.2317', 'l': '0.5435'}},
 {'id': '26650',
  'isResult': True,
  'h': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '1.56836', 'a': '1.36923'},
  'datetime': '2024-09-22 13:00:00',
  'forecast': {'w': '0.3886', 'd': '0.31', 'l': '0.3014'}},
 {'id': '26651',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '2.75588', 'a': '1.28411'},
  'datetime': '2024-09-22 15:30:00',
  'forecast': {'w': '0.72', 'd': '0.1782', 'l': '0.1018'}},
 {'id': '26652',
  'isResult': True,
  'h': {'id': '86', 'title': 'Newcastle United', 'short_title': 'NEW'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.34344', 'a': '1.26516'},
  'datetime': '2024-09-28 11:30:00',
  'forecast': {'w': '0.3867', 'd': '0.2946', 'l': '0.3187'}},
 {'id': '26653',
  'isResult': True,
  'h': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'},
  'a': {'id': '228', 'title': 'Fulham', 'short_title': 'FLH'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.614351', 'a': '1.43592'},
  'datetime': '2024-09-28 14:00:00',
  'forecast': {'w': '0.1181', 'd': '0.2591', 'l': '0.6228'}},
 {'id': '26654',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.10959', 'a': '1.12358'},
  'datetime': '2024-09-28 14:00:00',
  'forecast': {'w': '0.3388', 'd': '0.3145', 'l': '0.3467'}},
 {'id': '26655',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '4', 'a': '2'},
  'xG': {'h': '6.05305', 'a': '0.337909'},
  'datetime': '2024-09-28 14:00:00',
  'forecast': {'w': '0.9988', 'd': '0.0009', 'l': '0.0003'}},
 {'id': '26656',
  'isResult': True,
  'h': {'id': '244', 'title': 'Brentford', 'short_title': 'BRE'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.370222', 'a': '0.878617'},
  'datetime': '2024-09-28 14:00:00',
  'forecast': {'w': '0.1512', 'd': '0.3899', 'l': '0.4589'}},
 {'id': '26657',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '220', 'title': 'Brighton', 'short_title': 'BRI'},
  'goals': {'h': '4', 'a': '2'},
  'xG': {'h': '3.65839', 'a': '1.20712'},
  'datetime': '2024-09-28 14:00:00',
  'forecast': {'w': '0.8777', 'd': '0.0846', 'l': '0.0377'}},
 {'id': '26658',
  'isResult': True,
  'h': {'id': '229', 'title': 'Wolverhampton Wanderers', 'short_title': 'WOL'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.748925', 'a': '2.11724'},
  'datetime': '2024-09-28 16:30:00',
  'forecast': {'w': '0.0583', 'd': '0.1722', 'l': '0.7695'}},
 {'id': '26659',
  'isResult': True,
  'h': {'id': '285', 'title': 'Ipswich', 'short_title': 'IPS'},
  'a': {'id': '71', 'title': 'Aston Villa', 'short_title': 'AVL'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '1.84608', 'a': '1.14494'},
  'datetime': '2024-09-29 13:00:00',

In [14]:
matches_by_date = {
    'match_id':[],
    'home_team_id':[],
    'home_team_long_title':[],
    'home_team_short_title':[],
    'away_team_id':[],
    'away_team_long_title':[],
    'away_team_short_title':[],
    'home_goals':[],
    'away_goals':[],
    'home_xg':[],
    'away_xg':[],
    'datetime':[],
}

for match in dates_json_data:
    matches_by_date['match_id'].append(match['id'])
    matches_by_date['home_team_id'].append(match['h']['id'])
    matches_by_date['home_team_long_title'].append(match['h']['title'])
    matches_by_date['home_team_short_title'].append(match['h']['short_title'])
    matches_by_date['away_team_id'].append(match['a']['id'])
    matches_by_date['away_team_long_title'].append(match['a']['title'])
    matches_by_date['away_team_short_title'].append(match['a']['short_title'])
    matches_by_date['home_goals'].append(match['goals']['h'])
    matches_by_date['away_goals'].append(match['goals']['a'])
    matches_by_date['home_xg'].append(match['xG']['h'])
    matches_by_date['away_xg'].append(match['xG']['a'])
    matches_by_date['datetime'].append(match['datetime'])

df_dates = pd.DataFrame(matches_by_date)

In [15]:
df_dates.head()

,match_id,home_team_id,home_team_long_title,home_team_short_title,away_team_id,away_team_long_title,away_team_short_title,home_goals,away_goals,home_xg,away_xg,datetime
0,26602,89,Manchester United,MUN,228,Fulham,FLH,1,0,2.04268,0.418711,2024-08-16 19:00:00
1,26603,285,Ipswich,IPS,87,Liverpool,LIV,0,2,0.342601,3.92906,2024-08-17 11:30:00
2,26604,83,Arsenal,ARS,229,Wolverhampton Wanderers,WOL,2,0,1.6283,0.575835,2024-08-17 14:00:00
3,26605,72,Everton,EVE,220,Brighton,BRI,0,3,0.405325,1.79083,2024-08-17 14:00:00
4,26606,86,Newcastle United,NEW,74,Southampton,SOU,1,0,0.433489,1.95483,2024-08-17 14:00:00

In [16]:
df_dates['datetime'].min()

'2024-08-16 19:00:00'

In [17]:
df_dates['datetime'].max()

'2025-05-25 16:00:00'

In [18]:
def load_understat_data():
    # Step 1: Fetch the website
    url = 'https://understat.com/league/EPL'
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    # Step 2: Find the specific <script> tag containing the JSON data
    scripts = soup.find_all('script')
    dates_json_data = None

    # Step 3: Look for the script containing the teamsData
    for script in scripts:
        if 'datesData' in script.text:
            # Extract the content of the script tag as text
            dates_json_text = script.text
            # Step 4: Isolate the JSON data by splitting the string
            dates_json_text = dates_json_text.split("JSON.parse('")[1].split("')")[0]
            # Step 5: Decode the string by replacing escape characters
            dates_json_text = dates_json_text.encode('utf-8').decode('unicode_escape')
            # Step 6: Load the decoded text as a Python dictionary
            dates_json_data = json.loads(dates_json_text)
            break

    if dates_json_data:
        matches_by_date = {
            'match_id':[],
            'home_team_id':[],
            'home_team_long_title':[],
            'home_team_short_title':[],
            'away_team_id':[],
            'away_team_long_title':[],
            'away_team_short_title':[],
            'home_goals':[],
            'away_goals':[],
            'home_xg':[],
            'away_xg':[],
            'datetime':[],
        }

        for match in dates_json_data:
            matches_by_date['match_id'].append(match['id'])
            matches_by_date['home_team_id'].append(match['h']['id'])
            matches_by_date['home_team_long_title'].append(match['h']['title'])
            matches_by_date['home_team_short_title'].append(match['h']['short_title'])
            matches_by_date['away_team_id'].append(match['a']['id'])
            matches_by_date['away_team_long_title'].append(match['a']['title'])
            matches_by_date['away_team_short_title'].append(match['a']['short_title'])
            matches_by_date['home_goals'].append(match['goals']['h'])
            matches_by_date['away_goals'].append(match['goals']['a'])
            matches_by_date['home_xg'].append(match['xG']['h'])
            matches_by_date['away_xg'].append(match['xG']['a'])
            matches_by_date['datetime'].append(match['datetime'])

        df_dates = pd.DataFrame(matches_by_date)
        return df_dates
    else:
        print("Data could not be found")